service: sootam-problem
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    DYNAMODB_SOOTAM_TABLE: sootam-${sls:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-sootam-${sls:stage}
functions:
  Problem:
    handler: index.handler
    events:
      - httpApi:
          path: /problem
          method: post
      - httpApi:
          path: /problem
          method: get
      - httpApi:
          path: /getSingleProblem
          method: get
plugins:
  - serverless-latest-layer-version
  - serverless-offline

# resources:
#   Resources:
#     ProblemTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: sootam-${sls:stage}
#         AttributeDefinitions:
#           - AttributeName: pk
#             AttributeType: S
#           - AttributeName: sk
#             AttributeType: S
#           - AttributeName: answer
#             AttributeType: S
#           - AttributeName: chapter
#             AttributeType: S
#           - AttributeName: copyright
#             AttributeType: S
#           - AttributeName: createdAt
#             AttributeType: S
#           - AttributeName: month
#             AttributeType: S
#           - AttributeName: number
#             AttributeType: S
#           - AttributeName: problemImage
#             AttributeType: S
#           - AttributeName: solutionImage
#             AttributeType: S
#           - AttributeName: successRate
#             AttributeType: S
#           - AttributeName: testType
#             AttributeType: S
#           - AttributeName: unitId
#             AttributeType: S
#           - AttributeName: unitName
#             AttributeType: S
#           - AttributeName: updatedAt
#             AttributeType: S
#           - AttributeName: year
#             AttributeType: S
#         BillingMode: PAY_PER_REQUEST
#         KeySchema:
#           - AttributeName: pk
#             KeyType: HASH
#           - AttributeName: sk
#             KeyType: RANGE
#           - AttributeName: answer
#             KeyType: RANGE
#           - AttributeName: chapter
#             KeyType: RANGE
#           - AttributeName: copyright
#             KeyType: RANGE
#           - AttributeName: createdAt
#             KeyType: RANGE
#           - AttributeName: month
#             KeyType: RANGE
#           - AttributeName: number
#             KeyType: RANGE
#           - AttributeName: problemImage
#             KeyType: RANGE
#           - AttributeName: solutionImage
#             KeyType: RANGE
#           - AttributeName: successRate
#             KeyType: RANGE
#           - AttributeName: testType
#             KeyType: RANGE
#           - AttributeName: unitId
#             KeyType: RANGE
#           - AttributeName: unitName
#             KeyType: RANGE
#           - AttributeName: updatedAt
#             KeyType: RANGE
#           - AttributeName: year
#             KeyType: RANGE
#         GlobalSecondaryIndexes:
#           - IndexName: chapterIndex
#             KeySchema:
#               - AttributeName: chapter
#                 KeyType: HASH
#               - AttributeName: unitName
#                 KeyType: RANGE
#             Projection:
#               ProjectionType: ALL
#           - IndexName: unitNameIndex
#             KeySchema:
#               - AttributeName: unitName
#                 KeyType: HASH
#               - AttributeName: chapter
#                 KeyType: RANGE
#             Projection:
#               ProjectionType: ALL

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
