service: sootam-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    DYNAMODB_SOOTAM_TABLE: sootam-${sls:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-sootam-${sls:stage}
functions:
  createProblem:
    handler: index.handler
    events:
      - httpApi:
          path: /problem
          method: post
      - httpApi:
          path: /problem
          method: get
plugins:
  - serverless-latest-layer-version
  - serverless-offline

resources:
  Resources:
    ProblemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sootam-${sls:stage}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: chapter #단원
            AttributeType: S
          - AttributeName: unitName #형태소
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: chapterIndex
            KeySchema:
              - AttributeName: chapter
                KeyType: HASH
              - AttributeName: unitName
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: unitNameIndex
            KeySchema:
              - AttributeName: unitName
                KeyType: HASH
              - AttributeName: chapter
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
